#!/usr/bin/python2.7 
from streamlink.jtools import *

print 'PRZYKLAD: streamlink -l debug [ -o /tmp/fileName] "url" best'
cleanCMD()

import streamlink_cli.main
streamlink_cli.main.main()

cleanCMD()